### ISSUE TITLE
Change project name to "despolitizador"

### ISSUE THREAD

**Issue by LFeh** [LFeh/despolitizador#32]
It's a great ideia @luisfmsouza?

https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by luisfmsouza** [comment]
Yeah! We just need to create an `index.html` inside a new repo called `1500-translator` with this content:

```html
<!DOCTYPE html>
<meta charset="utf-8">
<title>Redirecting to https://www.felipefialho.com/despolitizador/</title>
<meta http-equiv="refresh" content="0; URL=https://www.felipefialho.com/despolitizador/">
<link rel="canonical" href="https://www.felipefialho.com/despolitizador/">
```

**Comment by LFeh** [comment]
I'll do it 😄

**Comment by LFeh** [comment]
Uhmmm, what is the problem? https://www.felipefialho.com/1500-translator 🤔

**Comment by luisfmsouza** [comment]
It's working perfectly!
