### ISSUE TITLE
Termos no plural traduzidos no singular

### ISSUE THREAD

**Issue by iWeya** [LFeh/despolitizador#40]
Palavras em plural são traduzidas no singular e sucedidas por um s. Por exemplo: "prerrogativas" torna-se "vantagem que pessoas comuns não tem(s)".
![image](https://user-images.githubusercontent.com/16453015/44003195-3c1b5c80-9e25-11e8-8804-332cb2d1ca64.png)

**Comment by LFeh** [comment]
#41 @matheusrod92 Seu pr ajuda nesses casos?

**Comment by matheusrod92** [comment]
@LFeh exatamente! São os erros que apareceram no teste deste PR: https://github.com/LFeh/despolitizador/pull/38

**Comment by LFeh** [comment]
Sensacional 👏👏👏
